### PR TITLE
changes for 3-FF

### PR DESCRIPTION
**Pull request by anonymousjaggu**
Final fixes as provided in google doc

### CODE REVIEW

**Review by maxceem — CHANGES_REQUESTED** [review]
Thanks, @anonymousjaggu.
Most of the issues are perfectly fixed, noticed just 2 things:

1. When checking if `Agreeability Type` is `Electronically-agreeable` or `DocuSignable` it's better not to use the title because it can be changed. 
     ```js
     <td>{{terms.agreeabilityType==='Electronically-agreeable'?terms.url:terms.agreeabilityType==='DocuSignable'?terms.docusignTemplateId:''}}</td>
      ```
    Instead it's better to use use `AgreeabilityTypeId`.
    We already have a constant configured for `DocuSignable` id: `AGREE_FOR_DOCUSIGN_TEMPLATE`. Please, also add another constant `AGREE_ELECTRONICALLY="5b2798b2-ae82-4210-9b4d-5d6428125ccb"` to the [config](https://github.com/topcoder-platform/admin-app/blob/feature/terms-managemenet-improvements/config.json) and [README](https://github.com/topcoder-platform/admin-app/blob/feature/terms-managemenet-improvements/README.md#L45).

    And use these constant to check if it's `Electronically-agreeable` or `DocuSignable`.

2. When I'm changing the page in the Dialog the height still jumps more than 1 page, see video https://monosnap.com/file/IGA0eQZ4k9d72TdnjO31ofG6EksXho and screenshot:
    image

     but during loading the next page:

     image

**Comment by anonymousjaggu** [comment]
Hi @maxceem thanks for the review
I have pushed the changes, please check

**Review by maxceem — CHANGES_REQUESTED** [review]
Thanks for quick update @anonymousjaggu .

2 is working good now.

1 is giving error for me on the Term listing page:

```
Unknown provider: ELECTRONICALLY_AGREEABLE_TEMPLATEProvider <- ELECTRONICALLY_AGREEABLE_TEMPLATE <- terms.TermsListController
```

image

Also, could you please, name the constant `AGREE_ELECTRONICALLY` instead of `ELECTRONICALLY_AGREEABLE_TEMPLATE` because we use such a name in the [Terms Service](https://github.com/topcoder-platform/terms-service/blob/dev/config/default.js#L37) so I'd like to keep the same for easier navigation.

**Comment by anonymousjaggu** [comment]
> Thanks for quick update @anonymousjaggu .
> 
> 2 is working good now.
> 
> 1 is giving error for me on the Term listing page:
> 
> ```
> Unknown provider: ELECTRONICALLY_AGREEABLE_TEMPLATEProvider <- ELECTRONICALLY_AGREEABLE_TEMPLATE <- terms.TermsListController
> ```
> 
> image
> 
> Also, could you please, name the constant `AGREE_ELECTRONICALLY` instead of `ELECTRONICALLY_AGREEABLE_TEMPLATE` because we use such a name in the [Terms Service](https://github.com/topcoder-platform/terms-service/blob/dev/config/default.js#L37) so I'd like to keep the same for easier navigation.

Not sure why you get the 2nd error can you please check by stopping the app and re-running `npm run build && npm run dev`

**Review by maxceem — APPROVED** [review]
Thanks, @anonymousjaggu.

All perfect now.

**Pull request merged**
