### PR TITLE
Feature/remove multiple resources

### PR DESCRIPTION
**Pull request by fdittz**
also corrected a bug that occurred when deleting a user on the last page, when the last page has only one user.

### CODE REVIEW

**Review by maxceem — CHANGES_REQUESTED** [review]
@fdittz works good for most of the cases.

Though if we remove multiple users and some users failed to be removed and some succeeded then we should remove from the list users which already removed successfully and keep users which we failed to remove:

image

It is already implemented this way for Users in the Groups

image

**Comment by maxceem** [comment]
@fdittz looks like it conflicts with some other PR I've merged from you. Could you please, resole the conflict.

**Comment by fdittz** [comment]
should be ok now

**Comment by maxceem** [comment]
Thanks, @fdittz. Resources API has an issue, so I cannot test this functionality at the moment. I would review this as soon as Resources API is fixed.

**Review by maxceem — APPROVED** [review]
@fdittz works good.

**Pull request merged**
