### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by huangqun**
Fix issues #48, #52, #53, #54 and #55

### CODE REVIEW

**Comment by ajefts** [comment]
@huangqun  I'm seeing this in dev when loading the tags page.  This is after I merged the latest PR.

image

**Comment by huangqun** [comment]
@ajefts I think these two new domains should be created on the dev server first?

**Comment by ajefts** [comment]
@huangqun Where would I be creating these?  I also see a reference in the error to "InformixId is not allowed"

**Comment by huangqun** [comment]
I think it's because of the inconsistence between the tags mock api and real api, I'll double check admin-app and see what changes are needed.

The informixId field is used to make sure we can sync the platforms / technologies into the tags, otherwise there's no way we can keep track. We can try to match by name but I think duplicate names are currently allowed so that won't work well.

**Comment by ajefts** [comment]
Hi @huangqun  - were you able to find anything here...?

**Comment by huangqun** [comment]
@ajefts as I stated in my previous comment, in order for the sync to work correct, we need to add a new column named "informixId" to the tags storage, is that possible? If not I think we need to change the way that sync works.

For the two new domains, do they need to be created in the tags database? Or just something in configuration?

**Comment by huangqun** [comment]
@ajefts in the meantime could you check if the fixes for issues #52, #53, #54 and #55 look good enough?

**Comment by huangqun** [comment]
@ajefts can you confirm if we can add the `informixId` field to tags service so we can sync properly?

**Pull request merged**
