### PR TITLE
changes for #161

### PR DESCRIPTION
**Pull request by anonymousjaggu**

### CODE REVIEW

**Comment by anonymousjaggu** [comment]
@maxceem except point ` Add "Type" between Title and Agreeability Type`
everything is done

**Review by maxceem — CHANGES_REQUESTED** [review]
@anonymousjaggu there are a few things:

1. Remove `Delete Terms` button in the Terms List (and don't requests the number of users in the Terms List):

    image

2. Also reduce the height of the RichTextEditor
    
    image

3. There are 2 additions regarding the deleting provided in this comment https://github.com/topcoder-platform/admin-app/issues/161#issuecomment-716813938

**Review by maxceem — CHANGES_REQUESTED** [review]
@anonymousjaggu just a small improvement:

1. Let's show `Delete` button disabled by default and only make it enabled after we loaded the users. Because now it is shown as enabled first, and after it becomes disabled after we loaded member, see video https://monosnap.com/file/SwKQDqYB2zVJXXzMvuznXgDo5Xdkba

    - Also, let's change the order of the button and number of users, so the `Delete` button doesn't jump:

        image

3. Just noticed one more thing. Let's add a new constant `DEFAULT_TERMS_TYPE_ID` instead of hardcoding the type title:

     ```js
      if (x.name == 'Contest') {
          $scope.newTerms.typeId = x.id;
       }
     ```

**Review by maxceem — CHANGES_REQUESTED** [review]
Everything is great. But the default type is not selected on the Terms Create page and there is an error in the console:

image

**Review by maxceem — APPROVED** [review]
Everything looks perfect @anonymousjaggu.

**Pull request merged**
